---
title: 'Exercises: Shiny reactivity'
output: pdf_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- # ```{r, message=FALSE, warning=FALSE, include=FALSE} -->
<!-- # knitr::opts_chunk$set(echo = FALSE) -->
<!-- # library(leaflet) -->
<!-- # ``` -->
<!-- #  -->
\begin{center}
\section{Exercises: Shiny Reactivity}
\end{center}

# Overview of Exercises

These exercises are designed to introduce the concept of reactivity, to provide you the ability to control when and how an app updates.

Create a new project for this set of exercises, it's not necessary to have a different one per exercise.

# Exercise 1

1.1 Duplicate the app from the last set of exercise you were able to complete, all we need is the map and slider to be working.

1.2 Add an additional control to the app that allows the user to select a few different map types from [rstudio.github.io/leaflet/basemaps.html](http://rstudio.github.io/leaflet/basemaps.html)

1.3 Currently, changing the basemap will result in the data points being regenerated. Use `eventReactive` to ensure that the data is only updated when the standard deviation controller is modified.

1.4 Publish the shiny app to the web - ensure that it works!


